// AUTOGENERATED FILE. DO NOT EDIT

//go:build js

package rl

const RAYLIB_VERSION_MAJOR = 5

const RAYLIB_VERSION_MINOR = 6

const RAYLIB_VERSION_PATCH = 0

const RAYLIB_VERSION = "5.6-dev"

const PI = 3.14159265358979323846

const DEG2RAD = (PI / 180.0)

const RAD2DEG = (180.0 / PI)

// Light Gray
var LIGHTGRAY = Color{200, 200, 200, 255}

// Gray
var GRAY = Color{130, 130, 130, 255}

// Dark Gray
var DARKGRAY = Color{80, 80, 80, 255}

// Yellow
var YELLOW = Color{253, 249, 0, 255}

// Gold
var GOLD = Color{255, 203, 0, 255}

// Orange
var ORANGE = Color{255, 161, 0, 255}

// Pink
var PINK = Color{255, 109, 194, 255}

// Red
var RED = Color{230, 41, 55, 255}

// Maroon
var MAROON = Color{190, 33, 55, 255}

// Green
var GREEN = Color{0, 228, 48, 255}

// Lime
var LIME = Color{0, 158, 47, 255}

// Dark Green
var DARKGREEN = Color{0, 117, 44, 255}

// Sky Blue
var SKYBLUE = Color{102, 191, 255, 255}

// Blue
var BLUE = Color{0, 121, 241, 255}

// Dark Blue
var DARKBLUE = Color{0, 82, 172, 255}

// Purple
var PURPLE = Color{200, 122, 255, 255}

// Violet
var VIOLET = Color{135, 60, 190, 255}

// Dark Purple
var DARKPURPLE = Color{112, 31, 126, 255}

// Beige
var BEIGE = Color{211, 176, 131, 255}

// Brown
var BROWN = Color{127, 106, 79, 255}

// Dark Brown
var DARKBROWN = Color{76, 63, 47, 255}

// White
var WHITE = Color{255, 255, 255, 255}

// Black
var BLACK = Color{0, 0, 0, 255}

// Blank (Transparent)
var BLANK = Color{0, 0, 0, 0}

// Magenta
var MAGENTA = Color{255, 0, 255, 255}

// My own White (raylib logo)
var RAYWHITE = Color{245, 245, 245, 255}

const MOUSE_LEFT_BUTTON = MOUSE_BUTTON_LEFT

const MOUSE_RIGHT_BUTTON = MOUSE_BUTTON_RIGHT

const MOUSE_MIDDLE_BUTTON = MOUSE_BUTTON_MIDDLE

const MATERIAL_MAP_DIFFUSE = MATERIAL_MAP_ALBEDO

const MATERIAL_MAP_SPECULAR = MATERIAL_MAP_METALNESS

const SHADER_LOC_MAP_DIFFUSE = SHADER_LOC_MAP_ALBEDO

const SHADER_LOC_MAP_SPECULAR = SHADER_LOC_MAP_METALNESS

// Compatibility hack for previous raylib versions
var GetMouseRay = GetScreenToWorldRay
